polkadot-evm/frontier

.github/workflows/cancel.yml, .github/workflows/rust.yml
Cancel old commit Github Actions if new ones have been pushed.
=> Cancel redundent Github Actions

rpc/src/lib.rs
rel https://github.com/paritytech/frontier/issues/7
=> eth_accounts RPC implementation

rpc/src/lib.rs
=> Implement hashrate for EthApi

rpc/primitives/src/lib.rs, rpc/src/lib.rs, template/runtime/src/lib.rs
=> Implement author Runtime API

rpc/core/src/eth.rs, rpc/src/lib.rs
rel #7 
EthApi::block_uncles_count_by_hash
=> Implement block_uncles_count_by_hash for EthApi

rpc/core/src/eth.rs, rpc/src/lib.rs
rel #7 
EthApi::uncle_by_block_number_and_index
=> Implement uncle_by_block_number_and_index for EthApi

rpc/core/src/eth.rs, rpc/src/lib.rs
rel #7 
EthApi::uncle_by_block_hash_and_index
=> Implement uncle_by_block_hash_and_index for EthApi

rpc/core/src/eth.rs, rpc/src/lib.rs
rel #7 
EthApi::block_uncles_count_by_number
=> Implement block_uncles_count_by_number for EthApi

Cargo.lock, frame/ethereum/src/lib.rs
=> pallet-ethereum: add number to hash mapping for Ethereum headers

frame/ethereum/src/lib.rs, rpc/core/src/eth.rs, rpc/primitives/src/lib.rs, rpc/src/lib.rs, template/runtime/src/lib.rs
=> Implement block_by_hash Runtime API

rpc/src/lib.rs
=> Implement submit_hashrate for EthApi

rpc/src/lib.rs
=> Implement submit_work for EthApi

frame/ethereum/src/lib.rs, rpc/core/src/eth.rs, rpc/primitives/src/lib.rs, rpc/src/lib.rs, template/runtime/src/lib.rs
=> Implement transaction_by_block_hash_and_index for Runtime API

rpc/src/lib.rs, template/node/src/rpc.rs, template/node/src/service.rs
=> Use Role::is_authority for is_mining EthApi implementation

frame/ethereum/src/lib.rs, rpc/core/src/eth.rs, rpc/primitives/src/lib.rs, rpc/src/lib.rs, template/runtime/src/lib.rs
=> Implement transaction_by_block_number_and_index for Runtime API

Cargo.lock, frame/ethereum/src/mock.rs, frame/ethereum/src/tests.rs, template/node/Cargo.toml, template/node/src/rpc.rs, template/runtime/src/lib.rs
This updates the Substrate vendor to master and fixes some whitespace/tab issues.
=> Update Substrate to master

LICENSE-APACHE2
=> LICENSE-APACHE2 += year+Copyright owner

Cargo.lock, frame/ethereum/src/lib.rs, frame/ethereum/src/mock.rs, rpc/src/lib.rs, template/runtime/src/lib.rs
@sorpaas I added the ChainId as a parameter of the Ethereum Pallet.
Let me know if you think there is a better way to support it.
=> Adds ChainId as parameter for Ethereum pallet

.editorconfig, .github/workflows/editorconfig.yml, README.md, frame/ethereum/src/lib.rs, frame/ethereum/src/mock.rs, rpc/primitives/src/lib.rs, rpc/src/lib.rs, template/runtime/src/lib.rs
Specifically, add a CI check that we use tabs instead of spaces!
=> Ensure editorconfig compliance

template/README.md, template/examples/contract-erc20/create-erc20.ts
It allows to explore blocks containing Eth transactions
=> Adds Transaction and Signature type for PolkadotJS

.editorconfig, Cargo.lock, Cargo.toml, frame/ethereum/src/lib.rs, frame/ethereum/src/mock.rs, template/node/src/command.rs, template/node/src/service.rs, template/runtime/src/lib.rs
`ChainId` is now defined in `pallet-evm`.
=> Remove duplicate chainId definition

README.md, rpc/primitives/src/lib.rs
=> Document EthereumRuntimeApi and README update

Cargo.lock, template/node/src/service.rs
Update the commit pin to current master.
=> Update Substrate commit pin

rpc/primitives/src/lib.rs, rpc/src/lib.rs, template/runtime/src/lib.rs
Makes error message more useful
=> include error in RPC response

frame/ethereum/src/lib.rs, frame/ethereum/src/tests.rs
Validate transactions before allow them enter the pool.
Closes #125
=> Signed extension

frame/ethereum/src/lib.rs, frame/ethereum/src/tests.rs
Populates the used_gas field on tx receipts using the value returned from pallet_evm.
=> Add used_gas to receipts.

Cargo.lock, frame/ethereum/src/lib.rs, frame/ethereum/src/tests.rs, template/runtime/src/lib.rs, ts-tests/tests/test-gas.ts
This fixes the ability for RPC to handle the case when `gas_price` is not provided.
=> Fix RPC call when gas price is not provided

frame/ethereum/src/lib.rs
Set the status info based on exit reason.
=> Set receipt status info

client/rpc/src/eth.rs, ts-tests/tests/test-revert-receipt.ts
Rel https://github.com/paritytech/frontier/issues/213
=> `status` field in transaction receipt (EIP658)

Cargo.lock, frame/ethereum/src/lib.rs, frame/ethereum/src/mock.rs, frame/evm/precompile/ed25519/src/lib.rs, frame/evm/precompile/modexp/src/lib.rs, primitives/rpc/src/lib.rs, template/runtime/src/lib.rs
This simplifies the trait definitions and make the state root fetcher more general.
=> Use Get<H256> for state root instead of EthereumExt

Cargo.lock, Cargo.toml, frame/dynamic-fee/Cargo.toml, frame/dynamic-fee/src/lib.rs
This adds a new dynamic fee pallet that can be used with evm's fee calculator to get dynamic min gas price.
=> Dynamic fee pallet for evm's FeeCalculator

client/rpc-core/src/types/filter.rs
This PR fixes a bug related to filters used on subscriptions or past events calls where the filter contains wildcards and more topics than the actual matching log. For example:
- Filter `[A, null, B]` will work on logs with topics `[A, Z, B]` but break on logs with a single topic `[A]`, as it tries to replace the wildcard at index out of bound `1`.
This PR makes sure that we only try to replace wildcards on existing indexes.
=> Fix topic wildcards bug

.gitignore, shell.nix
Same as found in Substrate repo.
=> Add shell.nix for better NixOS support

Cargo.lock, frame/ethereum/Cargo.toml, frame/evm/Cargo.toml, frame/evm/precompile/blake2/Cargo.toml, frame/evm/precompile/bn128/Cargo.toml, frame/evm/precompile/dispatch/Cargo.toml, frame/evm/precompile/ed25519/Cargo.toml, frame/evm/precompile/modexp/Cargo.toml, frame/evm/precompile/simple/Cargo.toml, primitives/evm/Cargo.toml
=> Upgrade evm to 0.23

client/rpc/src/eth.rs
Fix estimate_gas API(If the transaction fails, there will be an endless loop).
=> Fix estimate_gas

frame/ethereum/src/lib.rs
In the current implementation, there is some kind of transaction that fails and the transaction receipt is not available.
For example, after a failed transfer due to insufficient balance, trigger `ensure!(source_account.balance >= total_payment, Error::<T>::BalanceLow);`  in stack runner and early return in ethereum transact call.
=> Add more transaction validation

frame/ethereum/src/lib.rs
rel https://github.com/paritytech/frontier/pull/312#discussion_r591102095
Thanks @HackFisher!
=> Fix pre-log transaction processing

client/rpc/src/eth.rs
Sometimes the transaction is executed but the receipt is not found, this pr is used to fix this problem.
More info https://github.com/darwinia-network/darwinia-common/issues/567, https://github.com/darwinia-network/darwinia-common/issues/563
=> Correct load transactions by hash

README.md
=> Add missing Matrix link

client/rpc-core/src/types/filter.rs, client/rpc/src/eth.rs
Avoid perform the same Keccak256 calculation (when  `BloomInput::Raw`) for every block in the filter range. Do it once and re-use.
=> Pre-calculate `Bloom`

frame/ethereum/src/lib.rs
=> `min_gas_price` check

frame/dynamic-fee/CHANGELOG.md, frame/dynamic-fee/Cargo.toml, frame/dynamic-fee/src/lib.rs, template/node/Cargo.toml, template/node/src/chain_spec.rs, template/node/src/cli.rs, template/node/src/service.rs, template/runtime/Cargo.toml, template/runtime/src/lib.rs
Implemented following https://github.com/paritytech/frontier/blob/master/docs/frame/dynamic-fee.md
=> Update gas_price with dynamic-fee pallet

frame/evm/src/backend.rs, frame/evm/src/lib.rs, frame/evm/src/runner/stack.rs, frame/evm/src/tests.rs
With plan for Frontier releases paused, we can finally upgrade pallets to v2 format.
=> Revert revert #380

client/rpc/src/eth.rs
This PR removes some unnecessary trait bounds to the `AuxStore` trait. Frontier stopped using the aux store in https://github.com/paritytech/frontier/pull/295. This is a cleanup for that work.
=> Remove stray AuxStore trait bounds

client/rpc/src/eth.rs
Rel https://github.com/PureStake/moonbeam/issues/1130
=> Logs sorted by block number ASC instead DESC

frame/evm/src/backend.rs
You might consider having a `clippy` run in the CI to eliminate issues like this systemically.
=> Clean up unused Account and it's leftovers from the backend

frame/ethereum/src/lib.rs, frame/evm/src/lib.rs
Remove pallet-balances trait bound from pallet-evm (unused)
Make `EvmConfig` pub so its easier to customize
=> minor ux stuff

client/rpc/src/eth.rs, ts-tests/tests/test-fee-history.ts
Resolves https://github.com/paritytech/frontier/issues/592
=> `eth_feeHistory` handle non-existent block requests

Cargo.lock, client/consensus/Cargo.toml, client/db/Cargo.toml, client/mapping-sync/Cargo.toml, client/rpc-core/Cargo.toml, client/rpc/Cargo.toml, client/rpc/src/eth.rs, frame/base-fee/Cargo.toml, frame/dynamic-fee/Cargo.toml, frame/ethereum/Cargo.toml, frame/ethereum/src/lib.rs, frame/evm/Cargo.toml, frame/evm/precompile/bn128/Cargo.toml, frame/evm/precompile/dispatch/Cargo.toml, frame/evm/precompile/simple/Cargo.toml, frame/evm/src/runner/stack.rs, frame/evm/test-vector-support/Cargo.toml, primitives/consensus/Cargo.toml, primitives/evm/Cargo.toml, primitives/rpc/Cargo.toml, primitives/self-contained/Cargo.toml, primitives/storage/Cargo.toml, template/node/Cargo.toml, template/node/src/service.rs, template/runtime/Cargo.toml
=> Update substrate to polkadot-v0.9.18

Cargo.lock, client/rpc/Cargo.toml, client/rpc/src/eth/cache/mod.rs
see [CI](https://github.com/paritytech/frontier/runs/6175368350?check_suite_focus=true) for details.
=> Fix CI test

client/rpc-core/src/types/fee.rs, client/rpc-core/src/types/mod.rs, client/rpc/src/eth/fee.rs, client/rpc/src/eth/mod.rs, frame/evm/test-vector-support/Cargo.toml, frame/evm/test-vector-support/src/lib.rs, template/node/Cargo.toml, template/node/src/rpc.rs, template/node/src/service.rs
=> Make `aura` and `manual-seal` features more clear

client/rpc/src/eth/cache/tests.rs
=> Make test more stable

client/rpc/src/eth/cache/mod.rs
I found this little thing when reading code.
=> Use `BTreeMap::retain`

client/rpc-core/src/eth.rs, client/rpc-core/src/eth_pubsub.rs, client/rpc-core/src/lib.rs, client/rpc-core/src/net.rs, client/rpc/src/eth/block.rs, client/rpc/src/eth/cache/tests.rs, client/rpc/src/eth/client.rs, client/rpc/src/eth/execute.rs, client/rpc/src/eth/fee.rs, client/rpc/src/eth/filter.rs, client/rpc/src/eth/mining.rs, client/rpc/src/eth/mod.rs, client/rpc/src/eth/state.rs, client/rpc/src/eth/submit.rs, client/rpc/src/eth/transaction.rs, client/rpc/src/eth_pubsub.rs, client/rpc/src/lib.rs, client/rpc/src/net.rs, client/rpc/src/web3.rs, template/node/src/rpc.rs
Follow substrate naming, unify the naming of frontier rpc api
~~waiting for #653 to be merged firstly~~
=> Unify rpc api naming

Cargo.lock, client/rpc/Cargo.toml
=> Fix substrate-prometheus-endpoint dep

.github/dependabot.yml
=> Dependabot: ignore substrate deps

frame/ethereum/Cargo.toml, frame/evm/Cargo.toml
it currently only used in test and mock
=> pallet-balances should be in dev-dependencies

frame/ethereum/Cargo.toml, frame/evm/Cargo.toml
=> Remove useless pallet-balances/std features from pallet-ethereum and pallet-evm

frame/ethereum/src/lib.rs
Remove getter functions, use `pallet::getter` instead.
=> Use `pallet::getter` syntax

frame/base-fee/src/lib.rs, frame/dynamic-fee/src/lib.rs, frame/ethereum/src/lib.rs, frame/evm/src/lib.rs, frame/evm/src/runner/stack.rs, frame/hotfix-sufficients/src/lib.rs
=> Use named structs for pallet event

Cargo.lock, client/cli/Cargo.toml, client/consensus/Cargo.toml, client/db/Cargo.toml, client/mapping-sync/Cargo.toml, client/rpc/Cargo.toml, frame/base-fee/Cargo.toml, frame/dynamic-fee/Cargo.toml, frame/ethereum/Cargo.toml, frame/evm/Cargo.toml, frame/evm/precompile/bn128/Cargo.toml, frame/evm/precompile/dispatch/Cargo.toml, frame/evm/precompile/simple/Cargo.toml, frame/evm/test-vector-support/Cargo.toml, frame/hotfix-sufficients/Cargo.toml, primitives/consensus/Cargo.toml, primitives/dynamic-fee/Cargo.toml, primitives/ethereum/Cargo.toml, primitives/evm/Cargo.toml, primitives/rpc/Cargo.toml, primitives/self-contained/Cargo.toml, template/node/Cargo.toml, template/runtime/Cargo.toml, template/runtime/src/lib.rs
=> Release polkadot-v0.9.25

Cargo.lock, client/cli/Cargo.toml, template/node/Cargo.toml
update substrate to the commit 5677b91eb6ad8e280cf7dcbdb8990d31bd2d74b1, prepare for releasing polkadot-v0.9.26
Close #729
=> Update substrate to polkadot-v0.9.26

.github/workflows/rust.yml, frame/evm/src/benchmarking.rs, frame/hotfix-sufficients/src/benchmarking.rs, template/runtime/src/lib.rs
=> Add runtime-benchmarks feature check into CI

client/rpc/src/overrides/schema_v1_override.rs, client/rpc/src/overrides/schema_v2_override.rs, client/rpc/src/overrides/schema_v3_override.rs, primitives/storage/src/lib.rs
=> Add pallet storage item to primitives

client/rpc/src/eth/mod.rs, client/rpc/src/lib.rs
=> Export the format module

Cargo.lock, client/cli/Cargo.toml, client/consensus/Cargo.toml, client/db/Cargo.toml, client/mapping-sync/Cargo.toml, client/rpc/Cargo.toml, frame/base-fee/Cargo.toml, frame/dynamic-fee/Cargo.toml, frame/ethereum/Cargo.toml, frame/evm-chain-id/Cargo.toml, frame/evm/Cargo.toml, frame/evm/precompile/bn128/Cargo.toml, frame/evm/precompile/dispatch/Cargo.toml, frame/evm/precompile/simple/Cargo.toml, frame/evm/test-vector-support/Cargo.toml, frame/hotfix-sufficients/Cargo.toml, primitives/consensus/Cargo.toml, primitives/dynamic-fee/Cargo.toml, primitives/ethereum/Cargo.toml, primitives/evm/Cargo.toml, primitives/rpc/Cargo.toml, primitives/self-contained/Cargo.toml, template/node/Cargo.toml, template/runtime/Cargo.toml
Close #827
```bash
sed -i 's/master/polkadot-v0.9.27/g' `rg "substrate" -t toml -T lock -l`
```
=> Release polkadot-v0.9.27

template/README.md
=> Fix typo in README.md

frame/evm/src/lib.rs
See https://github.com/polkadot-evm/frontier/pull/1282#discussion_r1582959901
=> Use EVMFungibleAdapter as default implementation

Cargo.lock, primitives/account/Cargo.toml, primitives/account/src/lib.rs
=> `impl From<AccountId20> for Location`

template/runtime/src/lib.rs
This PR fixes wrong indent in template runtime.
=> style: Fix wrong indent in template runtime

precompiles/src/testing/account.rs
Adds `MockSignature` and `MockSigner` to precompile testing utilities
=> Add MockSignature and MockSigner testing utils

frame/evm/src/runner/stack.rs
**Description**
Adds a convenient debug level log on gas calculation.
=> Log effective gas calculation

client/rpc-core/src/eth.rs, client/rpc/src/eth/mod.rs, client/rpc/src/eth/submit.rs, client/rpc/src/eth_pubsub.rs, ts-tests/tests/test-pending-transactions-rpc.ts
Replaces the following stale PR: https://github.com/polkadot-evm/frontier/pull/1540
=> Add `eth_pendingTransactions` RPC

Cargo.lock
Update polkadot-sdk pins in Cargo.lock
=> Update polkadot-sdk pins in Cargo.lock
