rpc/src/lib.rs

Implement is_mining for EthApi

---

rpc/Cargo.toml
rpc/src/lib.rs
template/node/src/rpc.rs

Add support to access and use the sc_service::client::Client StorageProvider implementation through the client's instance. 
https://crates.parity.io/sc_client_api/backend/trait.StorageProvider.html

Add StorageProvider trait bound to Client

---

frame/ethereum/src/lib.rs
rpc/core/src/eth.rs
rpc/primitives/src/lib.rs
rpc/src/lib.rs
template/runtime/src/lib.rs

rel #7 
- pallet-ethereum: add `Transactions` StorageMap.
- `Transactions` insert `on_finalize`.
- New `frontier_rpc_primitives::Transaction` type.
- `transaction_by_hash` Runtime API implementation

Implement transaction_by_hash Runtime API

---

rpc/core/src/eth.rs
rpc/src/lib.rs

rel #7 
Removed the u64 optional parameter as it is not part of the spec:
https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getwork

Implement work for EthApi

---

frame/ethereum/src/lib.rs
rpc/core/src/eth.rs
rpc/primitives/src/lib.rs
rpc/src/lib.rs
template/runtime/src/lib.rs

rel #7 
Dependant on https://github.com/paritytech/substrate/pull/6279 approval.

Implement storage_at Runtime API

---

rpc/src/lib.rs

This PR adds support for the `frontier_rpc_core::types::BlockNumber` variants in `EthApi`. The goal is to enable calling the Runtime API with any valid `BlockId` number - past or present.
- New EthApi `impl` includes `native_block_number` method.
- Refactor the RPC calls that have `BlockNumber` parameters to use the new method. 
The new EthApi `impl` receives an optional `BlockNumber` argument (`Hash`, `Num`, `Latest`, `Earliest` or `Pending`) and translates it to its native (_substrate_) block number counterpart.
This native block number is used as the BlockId argument passed to the Runtime API call.

Add BlockNumber variant support for EthApi

---

template/runtime/src/lib.rs

Move `EVMModuleId` parameter type in a separate code block.

Small styling fixes

---

frame/ethereum/src/lib.rs
rpc/primitives/src/lib.rs
rpc/src/lib.rs
template/runtime/src/lib.rs

Rel #7 `block_by_hash` and `block_by_number`.
Adds support for `RichBlock` fields: `hash`, `extra_data`, `seal_fields`, `transactions`.
- Added a new `block_by_hash_with_statuses` rpc primitive function that returns a `(Block, Vec<TransactionStatus>)`. This is used to perform the `RichBlock::transactions` conversion.
- Updated the `block_by_number` rpc function to behave the same way.
- `seal_fields` returns a Vec<Bytes> containing block header's `mix_hash` and `nonce`.
**Additional note**
Originally `block_by_number` and `block_by_hash` rpc primitive functions returned the same response type (Block) accepting different parameters (hash or number).
Now they differ on the response type because `block_by_hash` alone is used for other pursposes (supporting the `BlockNumber` enum parameter in …

Support for additional RichBlock fields

---

frame/ethereum/src/lib.rs
rpc/primitives/src/lib.rs
rpc/src/lib.rs
template/runtime/src/lib.rs

Rel #7 `transaction_receipt`
This PR adds support for the `Receipt` fields: `block_hash`, `block_number`, `gas_used`, `logs` and `state_root` .
- Removed `transaction_status` rpc primitive function in favor of `transaction_by_hash`.
- Now `transaction_by_hash` additionally returns `ethereum::Receipt` by transaction index.

Support for additional Receipt fields

---

frame/ethereum/src/lib.rs
rpc/core/src/types/log.rs
rpc/primitives/src/lib.rs
rpc/src/lib.rs
template/runtime/src/lib.rs

rel #7 `transaction_receipt`
This PR adds support for the remaining fields in the `transaction_receipt` rpc call: `logs_bloom`, `cumulative_gas_used`, `transaction_log_index`, `log_index` and `removed`.
- `log_type` field is removed from the rpc core `Log` struct.
- `transaction_by_hash` runtime api now returns a `Vec<Receipt>`, necessary for calculating `cumulative_gas_used` and the `log_index`.

Support for additional Receipt fields #2

---

rpc/src/lib.rs

rel #7 transaction_by_hash, transaction_by_block_hash_and_index, transaction_by_block_number_and_index.
This PR adds support for the `Transaction` fields: `raw`, `chain_id`, `standard_v`, `v`, `r`, `s`.

Support for additional Transaction fields

---

frame/ethereum/src/lib.rs
frame/ethereum/src/mock.rs
rpc/src/lib.rs
template/runtime/src/lib.rs

rel #7 `block_by_hash` and `block_by_number`.
- Adds support for RichBlock field `author` and `miner`.
- Adds support for RichBlock field `size`.
- Cleanup.

Support for additional RichBlock fields #2

---

rpc/src/lib.rs

Rel #64 
This PR adds support for the boolean arg in `eth_getBlockByHash` and `eth_getBlockByNumber`.
- If `true`, it will return `BlockTransactions::Full(Vec<Transaction>)`
- If `false`, it will return `BlockTransactions::Hashes(Vec<H256>)`

Add support for BlockTransactions variants

---

Cargo.lock
Cargo.toml
template/test-utils/client/Cargo.toml
template/test-utils/client/src/lib.rs

Add basic executor and backend definitions, and implement functionality to create new test client. Genesis filling is not yet complete (it's now just `Default::default()`).

test-utils: test executor, backend and function to create test client

---

Cargo.lock
frame/ethereum/src/lib.rs
rpc/src/lib.rs
template/node/Cargo.toml
template/node/src/chain_spec.rs
template/runtime/src/lib.rs

Rel #78 
This PR sets the genesis block on `pallet-ethereum` storage and returns this block for requests using `BlockNumber::Earliest` as an argument.

Genesis block in pallet-ethereum

---

frame/ethereum/src/lib.rs
rpc/core/src/eth.rs
rpc/core/src/types/filter.rs
rpc/core/src/types/mod.rs
rpc/primitives/src/lib.rs
rpc/src/lib.rs
template/runtime/src/lib.rs

Add support and Runtime API implementation for eth_getLogs
Rel #83 
This PR adds support for `etg_getLogs`.
- Iterative process in `pallet-ethereum` to filter stored receipt logs.
- Runtime API implementation.
- Removed `limit` field in `Filter` struct, as not specified in https://eth.wiki/json-rpc/API#eth_getlogs.

Add support and Runtime API implementation for eth_getLogs

---

rpc/src/lib.rs
ts-tests/tests/test-block.ts

Fixes the timestamp currently being returned as UNIX timestamp in milliseconds.
ETH RPC is expecting UNIX timestamp in seconds.

Fixes bad timestamp formatting

---

Cargo.lock
Cargo.toml
consensus/Cargo.toml
consensus/primitives/Cargo.toml
consensus/primitives/src/lib.rs
consensus/src/aux_schema.rs
consensus/src/lib.rs
frame/ethereum/Cargo.toml
frame/ethereum/src/lib.rs
frame/ethereum/src/tests.rs
rpc/Cargo.toml
rpc/primitives/src/lib.rs
rpc/src/lib.rs
template/node/Cargo.toml
template/node/src/rpc.rs
template/node/src/service.rs
template/runtime/src/lib.rs

Currently, we store all the mappings of block hashes and transaction hashes directly in state storage. This is not optimal, as those hashes are repeated for every block. In addition, retrieval of those hashes from the runtime results in a large number of runtime API methods, which complicates implementations.
This PR attempts to fix those issues by moving the mapping from runtime state storage into the consensus auxiliary storage, by defining a custom block import struct. The import struct will read a post-runtime digest produced by runtime. The digest contains information about the block and transaction hash mappings, which are then moved to auxiliary store.
Substrate allows block imports to be stacked, so this frontier block import can wrap any other block imports in Substrate's …

Frontier-specific block import consensus

---

rpc/core/src/eth.rs
rpc/core/src/lib.rs
rpc/core/src/net.rs
rpc/src/lib.rs
template/node/src/rpc.rs
ts-tests/tests/test-deprecated.ts

* Remove non-standard JSON-RPC method definitions.
* Move `net_` APIs to proper `NetApi` trait.

Small clean-up of RPC methods

---

consensus/src/lib.rs
template/node/src/service.rs

Rel https://github.com/paritytech/substrate/pull/7014

Fix block import pipeline

---

consensus/src/lib.rs
template/node/src/service.rs

Part of #120
So validator / non-rpc node does not need to index all the extra data.
In later version, there should be a way to detect if the flag was use inconsistently similar to pruning mode.

Allow disable FrontierBlockImport

---

.gitmodules
Cargo.lock
Cargo.toml
consensus/Cargo.toml
frame/ethereum/Cargo.toml
rpc/Cargo.toml
rpc/core/src/eth.rs
rpc/primitives/Cargo.toml
rpc/primitives/src/lib.rs
rpc/src/lib.rs
template/node/Cargo.toml
template/node/src/rpc.rs
template/runtime/src/lib.rs

This removes all vendor-ed dependencies. Fixes https://github.com/paritytech/parity-common/issues/428 (due to update to `ethereum 0.3.0`).

Replace vendor ethereum with published ethereum crate and fix warnings

---

template/node/src/service.rs
ts-tests/tests/test-block.ts
ts-tests/tests/test-contract-methods.ts

include FrontierBlockImport when doing manual sealing to store ethereum block_hash and transactions into AuxStore

include FrontierBlockImport when doing manual sealing

---

consensus/src/aux_schema.rs
consensus/src/lib.rs
rpc/Cargo.toml
rpc/src/lib.rs

As part of the block import pipeline, the Frontier consensus inserts Ethereum and Substrate Hash mapping in the auxiliary storage.
If a fork happens, the mapping is not rolled back and will point to a block Hash that is no longer part of the canonical chain.
Following @crystalin  suggestion, this PR implements a one-to-many relation between Ethereum and Substrate block hashes (a single Ethereum Hash will map to a Vector of Substrate hashes).
The PR implementation asumes that:
- `HeaderBackend::header(BlockId)` only returns `Some` when the `BlockId` is part of the canonical chain.
- Only one Substrate Hash candidate between all the mapped by Ethereum Hash is part of the canonical chain.

Frontier consensus one-to-many mapping

---

rpc/src/eth_pubsub.rs

This fixes unwanted behaviour of using the best chain block when `to_block` filter parameter is None.

Fix filter `to_block`

---

Cargo.lock
rpc/Cargo.toml
rpc/src/eth.rs
rpc/src/eth_pubsub.rs
template/node/src/rpc.rs
template/node/src/service.rs

This is a proposal for switching to `HeaderBackend` trait to get the best canonical block, as `SelectChain` is currently not compatible with the Cumulus consensus block import strategy.

Use HeaderBackend instead SelectChain

---

rpc/primitives/src/lib.rs
rpc/src/eth.rs
template/runtime/src/lib.rs

Currently in `eth_getLogs` there are 2 runtime api calls per block + an additional keccak calculation per transaction hash within each block. This is - i.e. for web3's logs subscriptions with an initial past events payload - very expensive.
This PR mitigates that cost by adding `EthereumRuntimeRPCApi.current_all`, that returns all block information - Block, Receipt and Status - in a single runtime call.

Improve `eth_getLogs` runtime access

---

rpc/src/eth.rs
rpc/src/eth_pubsub.rs

Bug fixes:
- Use the correct index to access transactions in `eth_subscribe` log subscription.
- Add missing flag when no address or topics options are used in `eth_getLogs`.

Pubsub fixes

---

template/runtime/src/lib.rs

This PR changes the implementation of `fn gas_price` to use the `pallet_evm`'s associated type, `FeeCalculator`, rather than the `FixedGasPrice` struct directly. This code is more reuseable because it will not need to change when other `FeeCalculator` implementations are used.
And makes an analogous change to the chainId api.

Decouple Runtime API impls from specific structs

---

rpc/src/eth.rs
template/node/src/rpc.rs

`eth_syncing` was returning a `SyncStatus::Info` no matter what the actual network syncing status was. That is not the way this method works https://eth.wiki/json-rpc/API#eth_syncing. 
This PR fixes it to return SyncStatus::Info when the network `is_major_syncing`, and false (SyncStatus::None) otherwise.
**Additional note**
I couldn't find a built-in way of pulling the `best_seen_block` from the `NetworkService`, so while this PR fixes the expected response type, the response object still returns incomplete data. https://github.com/paritytech/substrate/issues/7311

Return correct response in `eth_syncing`

---

Cargo.lock
frame/ethereum/src/lib.rs
frame/ethereum/src/tests.rs
rpc/Cargo.toml
rpc/core/src/types/call_request.rs
rpc/primitives/src/lib.rs
rpc/src/eth.rs
rpc/src/lib.rs
template/runtime/src/lib.rs

This PR fixes RPC call `eth_estimateGas` and `eth_call` to handle exit reason and returned value. Error message will include the returned value like Ethereum. I also did some refactoring.

Fix eth_estimateGas and eth_call to match with Ethereum impl

---

template/node/src/cli.rs
template/node/src/command.rs
template/node/src/service.rs
ts-tests/tests/test-block.ts
ts-tests/tests/util.ts

Add support instant sealing which is useful for testing contracts.
NOTE: Although I creating a MockProvider to make waffle works, I still have to add a little delay (0.1s) between transaction to make it work but it's better then 6s

Support instant sealing

---

rpc/src/eth.rs

`eth_estimateGas` should handle exit reason like it's a normal `eth_call`

estimate_gas handle exit reason

---

.github/workflows/rustdoc.yml

Follow [this doc](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-create-ssh-deploy-key) to create the necessary keys. Configure Pages per screenshot. See example deployment here https://danforbes.github.io/frontier
Closes #177

Add GitHub Action to Publish Rustdocs as GitHub Page

---

frame/ethereum/src/lib.rs
frame/ethereum/src/tests.rs
rpc/src/eth.rs
ts-tests/tests/test-nonce.ts

Fixes #171 
This implementation uses the same approach as SystemApi `adjust_nonce` by iterating the pool and finding pending tx. https://github.com/paritytech/substrate/blob/46faa92432e3b85fde64e7fa504839ab81a462d1/utils/frame/rpc/system/src/lib.rs#L249
Although substrate will provide `(AccountId, Nonce)`, palletEthereum provides `(Address, Nonce)`. Not sure if we need to make it provide AccountId in order to treat transactions the same. Anyway I removed "Ethereum" prefix to make it easy compare

Pending nonce

---

Cargo.lock

This updates evm to v0.18.3. It fixes an off-by-one issue in call stack limit.

Update evm version

---

frame/ethereum/src/lib.rs
frame/ethereum/src/tests.rs

fixes #178 
Even if the EVM execution fails, it should not result in DispatchError, because the state is still changed. The error should be communicated via a Substrate event.

EVM execution error should not result in DispatchError

---

Cargo.lock
ts-tests/tests/test-block.ts
ts-tests/tests/test-revert-receipt.ts

Update `ethereum` to 0.4.2 which contains the correct transaction root calculation logic.
Fixes #180

Update ethereum version for correct transaction root calculation

---

rpc/core/src/types/filter.rs
rpc/core/src/types/mod.rs
rpc/src/eth.rs
rpc/src/eth_pubsub.rs

In this PR:
- VariadicValue now supports optional values as well as nested VariadicValues.
- Filtering logic lives now in frontier-rpc-core types and is used by both ethGetLogs and logs subscriptions.
- Support for conditional indexed parameters (conditionally matching _events_) (i.e. [Web3](https://web3js.readthedocs.io/en/v1.2.7/web3-eth-subscribe.html#id16)).
Rel https://github.com/paritytech/frontier/issues/145
----
**What's in here**
In `eth_subscribe::logs` and `eth_getLogs` we want to support the use of wilcards - `null` arguments in `topics` that match any value at a given position - and conditional indexed parameters - groups of values that may occur at a given position. This functionality is used by many Dapps.
Topic pattern match should accept:
`0x0` | `null` | …

Support topic wildcards and conditional indexed parameters

---

ts-tests/tests/test-subscription.ts

Some of `subscription.unsubscribe()` calls were missing on the tests. This leads to a race condition where `.on("data")` listener of previous steps captures data from subsequent steps.

Add required `unsubscribe` per test step

---

frame/evm/Cargo.toml
frame/evm/README.md
frame/evm/src/backend.rs
frame/evm/src/lib.rs
frame/evm/src/precompiles.rs
frame/evm/src/tests.rs

This adds `pallet-evm` code to Frontier, preserving all history by using git subtree. Not yet integrated with the rest of the codebase.

pallet-evm: move to Frontier (Part I)

---

Cargo.lock
frame/ethereum/Cargo.toml
frame/ethereum/src/lib.rs
frame/evm/Cargo.toml
frame/evm/src/lib.rs
frame/evm/src/runner/mod.rs
frame/evm/src/runner/stack.rs
primitives/evm/Cargo.toml
primitives/evm/src/lib.rs
rpc/Cargo.toml
rpc/primitives/Cargo.toml
rpc/primitives/src/lib.rs
template/node/Cargo.toml
template/runtime/Cargo.toml

Integrate local `pallet-evm`, and remove its dependency on Substrate `pallet-evm`.

pallet-evm: move to Frontier (Part III)

---

frame/ethereum/src/lib.rs
ts-tests/tests/test-block.ts
ts-tests/tests/test-revert-receipt.ts
ts-tests/tests/test-subscription.ts

Uses `frame_system::parent_hash` and `header.hash` to create a unique 256 bit `state_root` before storing the block.

Set block header `state_root`

---

.github/workflows/rustdoc.yml

It does not work now as the crate name has changed. I think in the future we can combine rustdoc with a proper landing page.

gh-pages: remove index.html file

---

frame/ethereum/src/lib.rs
frame/ethereum/src/mock.rs
frame/evm/src/lib.rs
frame/evm/src/tests.rs
template/runtime/src/lib.rs

This PR assigns a meaningful weight to pallet Ethereum's `transact` extrinsic, and updates the weight annotation of pallet EVM's extrinsics.
Some features:
* Weight is based only on gas limit, not gas price
* Customizable gas to weight mapping
* Default 1:1 gas weight mapping
* Uses Substrate's weight refund to return unused weight

Add weight annotation to pallet Ethereum's transact extrinsic

---

client/rpc/src/lib.rs
ts-tests/tests/test-revert-reason.ts

Rel https://github.com/paritytech/frontier/issues/218
- Change the message on `ExitError::Revert` to `VM Exception while processing transaction: revert`
- Tries to decode the UTF8 message data contained in the evm return value and append it as part of a reverted response error.

Add decoded revert reason to response message

---

frame/evm/Cargo.toml
primitives/evm/Cargo.toml

The crate requires features from `evm` that is only available after this patch version, so while `evm` is backward compatible and the versioning is okay, for Frontier the specific patch version must be present.

Require explictly evm 0.18.5 or newer

---

.github/workflows/docs.yml

Change the action name to `Docs` and the task name to `Deploy docs`, to keep it consistent with the rest of actions.

Docs CI naming

---

Cargo.lock
client/rpc/src/eth.rs
frame/ethereum/Cargo.toml
frame/ethereum/src/lib.rs
frame/ethereum/src/tests.rs
frame/evm/Cargo.toml
frame/evm/src/lib.rs
frame/evm/src/runner/builtin.rs
frame/evm/src/runner/mod.rs
frame/evm/src/runner/stack.rs
primitives/evm/Cargo.toml
primitives/rpc/src/lib.rs
template/runtime/src/lib.rs

This uses the new "estimate" flag available in `evm` 0.19 -- if enabled, all refunds are stripped, and SSTORE cost is always calculated at its highest value. Should be deal with most cases of #198.
This can be optionally combined with #229 (use Geth's binary search as fallback). However, it would be great to figure out a way to encourage people to submit issue reports if #229 is triggered (so that we can fix those cases "natively" in `evm`).

Support for evm "estimate" flag for RPC estimation

---

Cargo.lock
Cargo.toml
frame/ethereum/Cargo.toml
frame/evm/Cargo.toml
frame/evm/precompile/blake2/Cargo.toml
frame/evm/precompile/bn128/Cargo.toml
frame/evm/precompile/dispatch/Cargo.toml
frame/evm/precompile/dispatch/src/lib.rs
frame/evm/precompile/modexp/Cargo.toml
frame/evm/precompile/simple/Cargo.toml
frame/evm/src/runner/builtin.rs
primitives/evm/Cargo.toml
primitives/evm/src/precompile.rs

By adding this precompile, the EVM contract is able to interact with Substrate dispatchables as well as with `pallet-contracts`.

Add precompile support for Substrate dispatchables

---

frame/ethereum/src/lib.rs
frame/ethereum/src/tests.rs

When deploying a contract with web3 or remix, the ethereum transaction finally executed in the EVM stack runner, and no event to record the created address. Thus, This pr expands the `Executed` event in ethereum to include created contract address.

Expand Executed event

---

frame/evm/precompile/modexp/Cargo.toml
frame/evm/precompile/modexp/src/lib.rs

This PR fixes some logic issues with the ModExp precompile, and also adds some unit tests. Specifically, the previous logic seemed to crawl through the input buffer incorrectly when trying to pull out `base`, `exponent`, and `modulus` values.
There is still room for improvement around bounds-checking; the code will still gladly try to read an arbitrary size from the input buffer based on user input.

WIP Modexp fixes

---

client/rpc-core/src/types/block_number.rs
client/rpc-core/src/types/index.rs

This is a bit self-serving, but still adds value overall in being quite flexible in what it will accept. 
Generally the polkadot-js API will serialize bitLength <= 32 into decimal (a number of palettes will only use decimal values for these, not allowing hex), so this allows the `eth_*` RPCs to play along.
For both `BlockNumber` and `Index` we add a `u64` visitor, which handles decimal values. Additionally `BlockNumber` also aligns with `Index` in accepting `"1234"` decimal format string values.

Deserialize decimal inputs on BlockNumber

---

Cargo.lock
client/rpc-core/src/net.rs
client/rpc/src/eth.rs

Change the `peer_count` RPC returned type from `String` to `u32` to adapt web3 usage.

Update peer_count return type

---

Cargo.lock
frame/evm/precompile/ed25519/src/lib.rs
frame/evm/precompile/modexp/src/lib.rs

This PR builds off of #258 and adds some additional user-input checks as well as big-int-based bounds checking.
TODO: gas cost evaluation / enforcement:
https://eips.ethereum.org/EIPS/eip-198
https://eips.ethereum.org/EIPS/eip-2565

Additional precompile fixes

---

client/consensus/Cargo.toml
client/consensus/src/lib.rs
client/rpc-core/src/types/mod.rs
client/rpc-core/src/types/transaction.rs
client/rpc/src/eth.rs
client/rpc/src/lib.rs
template/node/Cargo.toml
template/node/src/rpc.rs
template/node/src/service.rs
ts-tests/tests/test-pending-pool.ts

This PR adds optional support for getting `Transaction` object when using `eth_getTransactionByHash` for pending transactions.
- Defines a shared `Mutex<HashMap<H256, Transaction>>` at service level.
- Use it at rpc level to insert and read data.
- Clear data on a service task.

Support pending transactions on rpc

---

client/rpc/src/eth.rs
ts-tests/tests/test-subscription.ts

- Fixes a bug where address matching was inverted in `eth_getLogs`.
- Only `VariadicValue::Single` parameter was supported in `EthApi` for address filtering.
Additionally:
- Follow the same filtering logic in both `EthApi` and `EthPubSubApi` to prevent further mismatches.
- Add more tests to cover different parameter combinations when asking for past events.

Bug fix + multi-address parameter support for `eth_getLogs` .

---

frame/ethereum/src/lib.rs
frame/ethereum/src/mock.rs
template/runtime/src/lib.rs

This PR removes the hard coded block gas limit from pallet ethereum and replaces it with a type in the `Config` trait. The template now uses `U256::MAX` instead of u32.
This allows chains using Frontier to use their own hard-coded value, calculate based on Substrate weight, or implement an adjustment algorithm in another pallet.

Abstract block gas limit

---

Cargo.lock
client/consensus/Cargo.toml
client/consensus/src/lib.rs
ts-tests/tests/test-block.ts

This PR proposes a solution for #78, mapping Ethereum <> Substrate genesis block hashes on the 1st block import using the runtime api.
Currently we depend on `ConsensusLog` digest items to do the mapping on the import pipeline. For genesis this is a problem because:
- Import pipeline is not executed for block 0.
- Digest logs are not set for block 0, so we cannot use `HeaderBackend`.
- There is no externalities api for the auxiliary storage.
So I ended up using the runtime api.

Genesis block hash mapping

---

frame/evm/src/lib.rs

This is done to let other pallets read the storage.
Signed-off-by: lovesh <lovesh.bond@gmail.com>

Make EVM pallet's storage items public.

---

Cargo.lock
client/consensus/src/lib.rs
frame/ethereum/src/lib.rs
primitives/consensus/Cargo.toml
primitives/consensus/src/lib.rs
template/node/src/service.rs

`ConsensusLog::PostHashes` (which is the legacy one) and `ConsensusLog::PostBlock` are generated by the runtime, while `ConsensusLog::PreBlock` is supplied by consensus engine and consumed by runtime. This separation paves the way for direct Ethereum block importing.

Introduce ConsensusLog::PostBlock and ConsensusLog::PreBlock

---

client/rpc-core/src/types/block.rs
client/rpc/src/eth.rs
ts-tests/tests/test-block.ts

Unrelated but small enough to go in the same PR I guess:
- Fix incorrect value on the Receipt's Log `transaction_hash` field.
- Default total_difficulty to `0x0` instead of `None`.

Rpc small fixes

---

client/rpc/src/eth_pubsub.rs

Until now using the `storage_changes_notification_stream` worked for us, but the approach does not fit correctly in the parachain context.
A typical use case in DApps is subscribing to new heads, then react to that event using the included block hash for something else (i.e. doing an additional RPC request). The import pipeline works different in the parachain context, where blocks are marked as _best_ once extracted back from a relay block.
This PR proposes using `import_notification_stream` instead together with the `ImportNotification::is_new_best` flag to emit events to subscribers only on best blocks. It is applied to all subscription Kinds except pending transactions, that make sense to be aware of as soon as they are in storage.

Switch to `best` import notification for pubsub

---

frame/ethereum/src/mock.rs
frame/evm/src/lib.rs
frame/evm/src/runner/mod.rs
frame/evm/src/runner/stack.rs
frame/evm/src/tests.rs
template/runtime/src/lib.rs

Projects using `pallet_ethereum` need a way to know about fee deducted
by EVM to take appropriate action on the fee like giving it to the
miner. This adds a type `OnChargeTransaction` to pallet's `Config` trait
similar to `OnChargeTransaction` of `pallet_transaction_payment`
Signed-off-by: lovesh <lovesh.bond@gmail.com>

Allow handling fee deductions done by EVM

---

Cargo.lock
Cargo.toml
client/consensus/src/lib.rs
client/db/src/lib.rs
client/mapping-sync/Cargo.toml
client/mapping-sync/src/lib.rs
client/mapping-sync/src/worker.rs
client/rpc/src/eth.rs
template/node/Cargo.toml
template/node/src/service.rs

This moves all Ethereum block mapping sync logics away from consensus layer.
* It allows chains to plug in Frontier mid-flight, while not requiring any mandatory node upgrade, as one do not need to modify the consensus layer.
* This separates consensus/runtime logic away from the more complicated RPC logic, which makes consensus/runtime interface (relatively) stable and suitable for audit.

Mapping sync worker

---

client/consensus/src/lib.rs
template/node/src/service.rs

It's redundant and unsafe. One can just use trait object to compose different block imports.

Remove enabled flag

---

client/consensus/src/lib.rs
client/mapping-sync/src/lib.rs
frame/ethereum/src/lib.rs
primitives/consensus/src/lib.rs
template/node/src/service.rs

`PreLog` uses `OpaqueDigestItemId::PreRuntime`, and `PostLog` uses `OpaqueDigestItemId::Consensus`. Therefore they should be separated.

Separate PreLog and PostLog

---

client/consensus/src/lib.rs
client/mapping-sync/src/lib.rs
frame/ethereum/src/lib.rs
primitives/consensus/src/lib.rs
template/node/src/service.rs

This adds support for pallet-ethereum to process an existing Ethereum block, encoded as a `PreLog`. If this is the case, then `transact` function is disabled.

Add support for PreLog in pallet-ethereum

---

Cargo.lock
client/rpc/Cargo.toml
client/rpc/src/eth.rs
client/rpc/src/lib.rs
template/node/src/service.rs

`frontier-filter-pool` and `frontier-pending-transactions` tasks of the node service template are useful for Frontier projects.
This PR moves both tasks into the `fc-rpc` crate as async functions.

Move template tasks into Frontier.

---

Cargo.lock
client/consensus/Cargo.toml
client/consensus/src/lib.rs
client/db/Cargo.toml
client/mapping-sync/Cargo.toml
client/rpc-core/Cargo.toml
client/rpc/Cargo.toml
frame/dynamic-fee/Cargo.toml
frame/ethereum/Cargo.toml
frame/ethereum/src/mock.rs
frame/evm/Cargo.toml
frame/evm/precompile/blake2/Cargo.toml
frame/evm/precompile/bn128/Cargo.toml
frame/evm/precompile/dispatch/Cargo.toml
frame/evm/precompile/ed25519/Cargo.toml
frame/evm/precompile/modexp/Cargo.toml
frame/evm/precompile/simple/Cargo.toml
frame/evm/src/tests.rs
primitives/consensus/Cargo.toml
primitives/consensus/src/lib.rs
primitives/evm/Cargo.toml
primitives/rpc/Cargo.toml
template/node/Cargo.toml
template/node/src/rpc.rs
template/node/src/service.rs
template/runtime/Cargo.toml
template/runtime/src/lib.rs
template/test-utils/client/Cargo.toml

This cherry-picks commits related to updating Substrate to v3.0 from Moonbeam's effort on the purestake/v0.7-moonbeam branch (https://github.com/purestake/frontier/tree/v0.7-moonbeam).
Related to #300, #306, and #308.
@drewstone I believe this addresses your #308 issues, although I don't recall exactly which commit was responsible.
This isn't quite done, but is very close.

Update Substrate to v3.0

---

client/rpc/src/eth.rs
frame/evm/src/lib.rs

Calling `storage_at` with the storage override rpc handler should return `H256::default()` instead of error if there is no value returned, consistent with the runtime api query.

The new rpc handle should returns the same data as the old one

---

.github/workflows/rust.yml
template/node/Cargo.toml
template/node/src/cli.rs
template/node/src/command.rs
template/node/src/service.rs
template/runtime/Cargo.toml
template/runtime/src/lib.rs
ts-tests/contracts/ExplicitRevertReason.sol
ts-tests/contracts/Test.sol
ts-tests/package-lock.json
ts-tests/tests/test-contract.ts
ts-tests/tests/test-gas.ts
ts-tests/truffle-config.js

Move manual seal node template under a feature flag

---

frame/evm/src/runner/stack.rs
ts-tests/tests/test-bloom.ts
ts-tests/tests/test-filter-api.ts
ts-tests/tests/test-subscription.ts

Referring to [This Answer](https://ethereum.stackexchange.com/questions/38019/is-it-possible-to-retrieve-an-event-log-from-a-reverted-transaction), we have tested it on the Ropsten and verified that this answer is correct.
A test contract like below:
```sol
pragma solidity ^0.7.0;
contract testlog {
event Log(uint256 a);
function test() public {
emit Log(1);
revert();
}
}
```
Submit a `test` call and get the transaction receipt like:
```sh
{
"blockHash":"0x9281ac790fe66da2fe8dd7b4c39836de45322064c05a1b9910650a4ae9dc62ac",
"blockNumber":14,
"contractAddress":null,
"cumulativeGasUsed":22250,
"from":"0xa3503704240f764cf91faba1775754b42fd2040f",
"gasUsed":22250,
"logs":[
{
"address":"0xfCA29754bB5d5a60F96cfba820F7e76A8E1b6f97",
"blockHash":"0x9281ac790fe66da2fe8dd7b4c39836de45322064c05a1b99106 …
```

If the transaction fails, the log data should also be revert

---

client/db/src/lib.rs
client/mapping-sync/src/lib.rs

Change the mapping sync logic so that:
* We differentiate two states of the syncer a) a syncing operation is ongoing, b) a new syncing operation can be started.
* Under a), we sync from top-down (instead of right now bottom-up), record the current most-bottom blocks, remove any if it's already in the database. The operation is called to end when the bottom block list is empty.
* Under b), we add the current block leaves to the bottom block list, and start a)

Correctly handle re-org in mapping sync

---

client/rpc/src/eth.rs
client/rpc/src/lib.rs

Moves `native_block_id`, `load_hash`, `onchain_storage_schema`, `is_canon` and `load_transactions` out of EthApi to the crate top level so it can be statically accessed.

Decouple backend access from EthApi

---

ts-tests/tests/test-precompiles.ts

This removes a call to `.only()` in the `ts-tests`, which causes this to be the only test run.
https://mochajs.org/#exclusive-tests
@drewstone If this needs to be handled differently, let me know. I'm not a `mocha` expert...

Remove only() call in tests

---

frame/ethereum/src/lib.rs
frame/ethereum/src/mock.rs
frame/evm/src/backend.rs
frame/evm/src/lib.rs
frame/evm/src/tests.rs
template/runtime/src/lib.rs

Solves #327 
This PR moves the associated type `BlockGasLimit` from `pallet_ethereum` to `pallet_evm`, and makes the data available in contracts.

Make block gas limit accessible in EVM contracts

---

Cargo.lock
client/rpc/Cargo.toml
client/rpc/src/eth.rs
client/rpc/src/lib.rs

An error message should be returned if there is a non-insufficient gas(fund) error occurs when `estimate_gas`.

Fix estimate_gas result when revert

---

client/rpc/src/overrides/schema_v1_override.rs
ts-tests/contracts/Storage.sol
ts-tests/tests/test-contract-storage.ts

We were using `U256::to_little_endian` to build the `StorageKey`, we need to use `U256::to_big_endian` instead.

Fix `storage_at` override bug

---

client/db/src/lib.rs
client/rpc/src/lib.rs

Remove legacy one-to-many block mapping from the database.
Currently we include the intermediate state root as part of the pallet-ethereum block so there is no way for two identical ethereum hashes under fork conditions: there will always be a unique association between substrate and ethereum hashes.
- Sets `BLOCK_MAPPING` column to hold a single `Block::Hash` value.
- Adapt the `block_hash` function to return an `Option<Block::Hash>` instead a `Vec`.
- Simplifies the `frontier_backend_client::load_hash` function to assume there is indeed always a one-to-one association.

Switch to one-to-one block mapping in db

---

Cargo.lock
client/CHANGELOG.md
client/rpc/Cargo.toml
client/rpc/src/eth.rs
client/rpc/src/eth_pubsub.rs
client/rpc/src/lib.rs
client/rpc/src/overrides/mod.rs
template/node/src/rpc.rs
ts-tests/tests/test-web3api.ts

We still needed to use this on `eth_getLogs` method, `EthFilterApi` as well as in `EthPubSubApi`.

Schema override TODOs

---

client/rpc/src/eth_pubsub.rs

Subscription logs `transaction_index` field had the wrong value.

Fix `pubsub` transaction index

---

Cargo.lock
client/rpc-core/CHANGELOG.md
client/rpc-core/Cargo.toml
client/rpc-core/src/types/filter.rs
client/rpc/Cargo.toml
client/rpc/src/eth.rs
template/node/src/cli.rs
template/node/src/rpc.rs
template/node/src/service.rs

This PR introduces changes to fix some of our outstanding work on the past events queries:
- CLI argument to control the maximum number of logs returned in a single request. Default 10,000.
- Execution limit for a single request. Default 10 seconds.
- Use of logs bloom to pre-filter.
The goal is to have a predictable performance on both `eth_getLogs` and `eth_subscribe` for `logs`.

Past events TODOs

---

Cargo.lock
frame/evm/precompile/bn128/Cargo.toml

Updates substrate-bn to the recently published version 0.6 to avoid rand 0.5.6 package issues when importing bn-128 precompiles

Update substrate-bn to 0.6

---

Cargo.lock
frame/ethereum/src/lib.rs

This ensures that genesis block number is set to zero not one.

Fix genesis block number generation

---

client/rpc-core/src/net.rs
client/rpc-core/src/types/mod.rs
client/rpc-core/src/types/sync.rs
client/rpc/src/eth.rs
template/node/src/rpc.rs
ts-tests/tests/test-netapi.ts

There are inconsistencies on the response format expected when calling `net_peerCount`. Some tools/dapps expect decimal format, others hex.
This PR adds a bool `peer_count_as_hex` parameter to `NetApi`, so projects instantiating the handler at service level can decide which format to use. Defaulted to `false` in the template.

Optional `net_peerCount` response format

---

client/mapping-sync/src/worker.rs

These mapping worker logs might be confusing and easy to be misunderstood as a synchronization problem.

Update worker log level

---

client/rpc/CHANGELOG.md
client/rpc/src/eth.rs
client/rpc/src/lib.rs

If `OutOfFund` happened, should return right now instead of continuing with the estimating process.

Estimate_gas return issues

---

client/rpc/src/eth.rs

This addresses a `// TODO` in RPC calls where we currently use `U256::max_value()` as a default value when no `gas_limit` is provided.
Concretely, this solves a problem where nested contract calls in a gas estimation request return a value too large for a 53 bit integer, which triggers errors in javascript clients.
This relates to #280. It doesn't fix it, but it reduces the most extreme cases.

Use block's gas limit as default instead of U256::max_value()

---

frame/evm/precompile/bn128/src/lib.rs

This adds bounds checks in bn128 precompiles before calling `from_slice()`.

BN128 Bounds Checks

---

frame/dynamic-fee/src/lib.rs
frame/ethereum/src/lib.rs
template/runtime/src/lib.rs

1. There is no need to output the target gas price event for each block.
2. Move `kill()` into the `on_initialize`, then you can viewTargetMinGasPrice value in explorer.
3. Add `Pays::No` in ethereum transact call.

Remove TargetMinGasPrice event

---

template/node/src/command.rs
template/node/src/service.rs

Remove frontier offchain db on `purge-chain` subcommand

---

primitives/rpc/src/lib.rs
ts-tests/contracts/Test.sol
ts-tests/tests/test-contract-methods.ts
ts-tests/tests/test-gas.ts

`#[skip_initialize_block]` prevents block `X` initialization for the `call` and `create` runtime api methods. Without it, `frame_system` will initialize it's state to block number `X+1`.
Solidity `block.number` is expected to return the same height at which the runtime call was made. `frame_system::block_number` is used to get the environmental block number from within the evm execution context.
To reproduce this on Kovan:
- Copy code below in a `test.js` file (replace `{TOKEN}` with your token).
- `npm init && npm i ethers && node test.js`
```
// [test.js]
const ethers = require('ethers');
const providerRPC = {
kovan: {
name: 'kovan',
rpc: 'https://eth-kovan.alchemyapi.io/v2/{TOKEN}',
chainId: 42,
},
};
let abi = [
{
inputs: [],
stateMutability: 'nonpayable',
type: 'constructor',
},
{ …
```

Use `skip_initialize_block` for `call` and `create`

---

Cargo.lock
client/mapping-sync/Cargo.toml
frame/ethereum/Cargo.toml
frame/ethereum/src/mock.rs

We're going to switch to partial rolling releases due to lack of corresponding Substrate releases. That is, we only release what we can but not everything else. You can easily distinguish released crates and unreleased ones by whether they have the `-dev` suffix.
If your dependency has any of the crates that we are not able to release, you'll unfortunately have to stick with git dependencies or vendored dependencies.
Fix a missing feature issue in the `libsecp256k1` version bump.

Fix remaining release issues

---

client/rpc/src/eth_pubsub.rs
primitives/rpc/src/lib.rs
template/runtime/src/lib.rs
ts-tests/tests/test-subscription.ts

In `Kind::NewPendingTransactions`, current approach of subscribing to storage changes t is not good for many reasons, and will lead to problems because:
- currently it does not make use of the schema overrides. This is not critical, as subscriptions are "from now on", but still incorrect as may force to do a client upgrade when doing a runtime upgrade that affects that storage item.
- Moreover, is coupled to the pallet-ethereum storage when this has nothing to do with storage.
- `pallet-ethereum::Pending` data is appended when the transact dispatchable is actually dispatched, not when the unsigned extrinsic is preliminarily added to the pool. The pending transaction WS subscription is supposed to notify the subscriber when the transaction is in the ready queue, not when whatever we do in …

Use `TransactionPool` notification stream in pusbub

---

frame/ethereum/src/lib.rs
frame/ethereum/src/tests.rs

This replaces the previous transaction prioritization logic with a simple prioritization by gas price.
This PR takes the opinion that it is not pallet-ethereum's job to ensure that ethereum transactions are prioritized fairly with "normal" frame transactions. Rather it it pallet ethereum's job to prioritize transactions the way ethereum does.
It is the up to any runtime that uses both frame- and pallet-ethereum-style transactions to make sure they are prioritized fairly relative to one another. (This concern is not addressed in this PR.)

Prioritize by gas price

---

client/rpc/CHANGELOG.md
client/rpc/src/eth.rs

This PR protects against a DOS attack consisting in making an rpc call forcing the node to perform many calculations.
Indeed, it is possible to ask for an estimate of the gas cost by providing an excessively high amount of gas, an attacker can then easily force the node to do a lot of computation by asking to estimate a call that contains an infinite loop for example.
To mitigate this problem, this RP ensures that the amount of gas provided does not exceed the gas limit of the current block.

fix(estimate_gas): Ensure that provided gas limit it never larger than current block's gas limit

---

Cargo.lock
frame/dynamic-fee/CHANGELOG.md
frame/dynamic-fee/Cargo.toml
frame/dynamic-fee/src/lib.rs

To avoid potential abuse of unsigned transactions in dynamic fee pallet. This implementation refers to [Timestamp Pallet](https://github.com/paritytech/substrate/blob/master/frame/timestamp/src/lib.rs).

Update `TargetMinGasPrice` once in a block

---

template/README.md
template/node/src/chain_spec.rs
template/runtime/src/lib.rs
template/utils/README.md
template/utils/package-lock.json
ts-tests/package-lock.json

> Insecure Credential Storage - https://npmjs.com/advisories/877
> No fix available
> node_modules/web3
- Clarify for those looking how to make a stand alone template, and use URLs to point correctly from wherever it is accessed (in this repo or via the stand-alone devhub generated one, that copies this README in it's generation)

Update Template use and utils

---

Cargo.lock
frame/dynamic-fee/Cargo.toml
frame/ethereum/Cargo.toml
frame/evm/Cargo.toml
primitives/storage/Cargo.toml

Making new Frontier releases while keeping up-to-date with current Substrate has become an impossible task for now. As a result, we're dropping rolling releases for Frontier and making a final Frontier pallet release here.
Until the Substrate release issue is fixed, it's recommended that you follow Substrate master tag and Frontier master tag instead of Cargo versions. This does pose greater stability risk for end users, but from now on we aim to break master as little as possible.
Please continue to follow rolling release guidelines when making PRs, as the releases will be resumed as soon as Substrate release pipeline is resolved.

Final pallet release

---

frame/ethereum/CHANGELOG.md
frame/ethereum/src/lib.rs

Currently we only unwrap created contract address or `H160::default`, that is, we are only covering `Create`. This PR fixes that to use `to` for `Call` desposited events.

Fix `Event::Executed` for transaction `Call`.

---

frame/ethereum/src/lib.rs
ts-tests/tests/test-transaction-cost.ts

This PR fixes an issue where invalid transactions are stored on pallet-ethereum storage for free.
- User `A` sends transaction with input data which's cost is greater than the gas limit.
- The EVM will early exit if that transaction cost cannot be paid, and the account `nonce` is not increased in that case.
- Currently the `pallet_evm::runner` does not _Error_ in that case, so pallet-ethereum inserts the transaction metadata in it's storage. At this point, once the block is sealed, that transaction is mapped to the block, even if it didn't increase the `nonce` for user `A`, thus bloating the runtime storage for free (as the used gas still 0 and the fees are refunded in the runner after).
Transactions that cannot pay for the transaction cost itself should be discarded, its source account …

Validate transaction cost

---

frame/evm/precompile/dispatch/src/lib.rs

This small PR removes an unnecessary trait bound from the definition of the `Dispatch` struct. This bound is already included in a `where` clause on the implementation of the `Precompile` trait.

Remove unnecessary trait bound on `Dispatch` precompile

---

frame/ethereum/Cargo.toml

In pallet ethereum, libsecp256k1 is only used in the tests, so it does not need to be a full dependency.

Make libsecp256k1 a dev dependency

---

client/rpc/src/eth.rs
client/rpc/src/lib.rs

The receipt for a transaction that is not included in the canonical chain should be null
Fixes https://github.com/paritytech/frontier/issues/473

Returns null receipt for non-canonical block transactions

---

Cargo.lock
client/rpc-core/CHANGELOG.md
client/rpc-core/src/types/mod.rs
client/rpc-core/src/types/transaction.rs
client/rpc/CHANGELOG.md
client/rpc/Cargo.toml
client/rpc/src/eth.rs
frame/dynamic-fee/src/lib.rs
frame/ethereum/src/mock.rs
frame/evm/src/mock.rs
template/node/src/command.rs
template/node/src/rpc.rs
template/node/src/service.rs
template/runtime/src/lib.rs

This PR removes the need for using the custom `Mutex` to handle pending transactions and the service background task that mantains it. Instead makes use of the transaction graph interface to get ethereum transactions from the `ready` and `future` queues. 
**Pros**
Uses substrate native Api.
**Cons**
Additional access to the runtime to filter the ethereum Calls.
Rel https://github.com/paritytech/substrate/pull/9726
Closes https://github.com/paritytech/frontier/pull/403 (for convenience, easier to redo than to fix all conflicts)

Refactor pending transactions

---

Cargo.lock
client/rpc/Cargo.toml
client/rpc/src/eth.rs
client/rpc/src/lib.rs
template/node/src/rpc.rs

When calling RPC (mainly related to logs) a lot of time is spent fetching the data from the database.
This PR adds an LRU cache to avoid reaching the database when many requests are related to the same block (this happen a lot with block explorers).
The cache use the substrate block hash as a key, as it won't change in case of reorg (instead of block id/height).
- Since these RPC apis are not async, this PR doesn't use async. When a block is not cached, it will fetch the database **while not holding the lock**, then obtain the lock only to insert the block data. It means while a block data is fetched other requests will also fetch the database. Only when one of them will put the data into the cache that subsequent requests will use the cache and not reach the DB. This is suboptimal but …

Add LRU cache for eth block data and transactions statuses

---

frame/evm/precompile/blake2/src/lib.rs
frame/evm/precompile/dispatch/src/lib.rs
frame/evm/test-vector-support/src/lib.rs

This PR removes a few unused imports that cause build warnings. This only covers library code, not the template (which is a very noisy build and a separate issue).

Prune unused imports

---

frame/ethereum/src/lib.rs

The original `find_pre_log` check causes an unexpected error when PreLog exists.
```rs
// on_initialize(_)
if let Ok(log) = fp_consensus::find_pre_log(&frame_system::Pallet::<T>::digest()) {
...
Self::do_transact(source, transaction).expect("pre-block transaction verification failed; the block cannot be built");
....
}
do_transact(_, _) {
// Always return Ok(...) in the case of PreLog exists, right? 
// Because this transaction cames from on_initialize()  and digest contains PreLog
ensure!(fp_consensus::find_pre_log(&frame_system::Pallet::<T>::digest()).is_err(), Error::<T>::PreLogExists);
...
}
```

Move `find_pre_log` out of `do_transact`

---

client/rpc/src/eth.rs

revert #501 and adds a cleaner fix that does not introduce regression for contracts that revert when not given enough gas.
If the first execution revert, there are two possible cases:
1. It can revert because the called contract feels that it does not have enough gas left to continue
2. Or it can revert for another reason unrelated to gas.
Depending on the case, the error message to be returned must be different.
I assume that if the current block gas limit is not enough, then the revert is not due to a lack of gas from the user. So to dissociate the two cases, we replay the execution with the current block gas limit.

estimateGas: if the first execution revert, it's not an exceeds allowance

---

frame/evm/src/lib.rs
frame/evm/src/tests.rs

Rel https://github.com/paritytech/substrate/issues/10117
A temporary patch while there is a substrate upstream solution.

Patch substrate bug for refund on 0 ED chains

---

client/rpc/src/eth.rs

This tiny change prevents an issue where the returned value from `estimate_gas` can be below the amount actually used.
Note that this matches the Geth implementation: https://github.com/ethereum/go-ethereum/blob/master/accounts/abi/bind/backends/simulated.go#L550

Use `mid` instead of `highest` for estimate_gas binary search

---

client/rpc/src/eth.rs

For "simple transfer" the gas estimated should be 21000, but currently is 22312.
This is due to the fact that we close the binary search as soon as the result varies by less than 10%.
For the particular case of a simple transfer, there is no need to do a binary search, we must return 21000 directly.

estimate_gas: for simple transfer to simple account, return 21000 directly

---

client/rpc/src/eth_pubsub.rs
frame/ethereum/src/lib.rs
primitives/consensus/src/lib.rs
ts-tests/tests/test-transaction-version.ts

Some hashes were still being calculated legacy-style. Rel https://github.com/paritytech/frontier/issues/528

Fix transaction hashing

---

frame/ethereum/src/lib.rs

`EthereumStorageSchema` always goes with the runtime. So we should always sync its value on runtime upgrade.

Sync EtheruemStorageSchema on runtime upgrade

---

frame/evm/src/lib.rs
frame/evm/src/tests.rs

Inserting to `AccountCodes` directly without increasing Account reference (`inc_consumers`) leads to errors if that account is removed later on using the `remove_account` function:
```
pub fn remove_account(address: &H160) {
if <AccountCodes<T>>::contains_key(address) {
let account_id = T::AddressMapping::into_account_id(*address);
let _ = frame_system::Pallet::<T>::dec_consumers(&account_id);
}
<AccountCodes<T>>::remove(address);
<AccountStorages<T>>::remove_prefix(address, None);
}
```
Above `AccountCodes` key will exists, but never increased the consumers:
```
/// Decrement the reference counter on an account. This *MUST* only be done once for every time
/// you called `inc_consumers` on `who`.
pub fn dec_consumers(who: &T::AccountId)
```
In addition to that, in order to increase the …

Fix bug in `pallet-evm` genesis account creation

---

Cargo.lock
client/rpc/Cargo.toml
client/rpc/src/eth.rs
ts-tests/tests/test-balance.ts
ts-tests/tests/test-contract-storage.ts
ts-tests/tests/test-contract.ts

This PR adds support for `pending` tag in:
- `eth_getBalance`
- `eth_getCode`
- `eth_getStorageAt`
In addition to adding `pending` tag support to it, `eth_call` uses the `BlockNumber` parameter (previously not used).
**Note:** if the pending contract is a _future_ txn and some of the txns in the ready queue satisfies the requirements of the future one, this PR's approach won't do it because we only apply ready txns. @sorpaas I think current proposal is enough, but please let me know.

Add `Pending` tag support

---

frame/evm/src/tests.rs

I find such an issue when looking back to https://github.com/paritytech/frontier/pull/420 . From the ts test execution result, `reducible_balance` should not include `ExistentialDeposit`.  `ExistentialDeposit = 0` in the rs test hides this error.

Fix incorrect `reducible_balance` unit test

---

frame/base-fee/src/lib.rs
template/runtime/src/lib.rs

Introduces a new associated type to `pallet-base-fee` for allowing to configure the default `IsActive` storage item. Also used `on_runtime_upgrade`.

Add `IsActive` associated type to `pallet-base-fee`

---

Cargo.lock
client/rpc-core/Cargo.toml
client/rpc-core/src/types/call_request.rs
client/rpc-core/src/types/transaction_request.rs
client/rpc/Cargo.toml
client/rpc/src/eth.rs
client/rpc/src/eth_pubsub.rs
client/rpc/src/lib.rs
client/rpc/src/overrides/mod.rs
client/rpc/src/overrides/schema_v1_override.rs
client/rpc/src/overrides/schema_v2_override.rs
client/rpc/src/overrides/schema_v3_override.rs
frame/ethereum/Cargo.toml
frame/ethereum/src/lib.rs
frame/evm/Cargo.toml
frame/evm/test-vector-support/Cargo.toml
primitives/consensus/Cargo.toml
primitives/evm/Cargo.toml
primitives/rpc/Cargo.toml
primitives/rpc/src/lib.rs
primitives/self-contained/Cargo.toml
template/node/src/rpc.rs
template/runtime/src/lib.rs
ts-tests/tests/test-gas.ts

To properly calculate the block's `receipts_root`, receipts need to be rlp encoded using the `status` and the `cumulative_gas_used`. Additionally enveloped (2930 and 1559) transactions' receipts are encoded with the prepended type byte.
As shown [in geth](https://github.com/ethereum/go-ethereum/blob/e4f570fcc67aa2df489666cc08568c637024fd3c/core/types/receipt.go#L137-L151).

Switch to `ReceiptsV3` to properly encode and store receipts data

---

Cargo.lock
client/rpc-core/src/eth.rs
client/rpc/Cargo.toml
client/rpc/src/eth.rs
primitives/consensus/src/lib.rs
template/node/src/rpc.rs
template/node/src/service.rs

Follow-up to #479 . Moves cache into a dedicated async task managing the cache, which is requested by various RPC functions using channels.
In the original code, in the scenario of a first request starting to fetch block data: a second request requesting the same block data before the first request cached the data would lead to fetch again the block data instead of waiting for the first result.
This new code prevents to fetch the same block data multiple times, and will instead add all awaiting requesters to a pending list which will get the data once it is fetched (once).

Async LRU cache for Ethereum block data

---

frame/evm/precompile/modexp/src/lib.rs

This PR properly handles an exponent of 0 in the ModExp precompile.

Handle 0 exponent with fudged length correctly in ModExp

---

frame/ethereum/src/lib.rs

This was left in https://github.com/paritytech/frontier/pull/541 and was uncovered by tests in Moonbeam. I will try to find some time to port our TS test setup to Frontier, where we run all tests for every supported ethereum transaction type.

Fix `used_gas` bug

---

primitives/self-contained/src/unchecked_extrinsic.rs

For some reason `From<UncheckedExtrinsic>` wasn't implemented for `sp_runtime::OpaqueExtrinsic`. But it should be to avoid incorrect usage of `fp_self_contained::UncheckedExtrinsic` in runtime of substrate-based nodes.

Implement missed From<UncheckedExtrinsic> for OpaqueExtrinsic

---

client/rpc-core/src/types/call_request.rs
client/rpc-core/src/types/transaction.rs
client/rpc-core/src/types/transaction_request.rs
client/rpc/src/eth.rs
ts-tests/tests/test-transaction-version.ts

Add support for optional `type` in transaction request. See [geth](https://github.com/ethereum/go-ethereum/blob/c503f98f6d5e80e079c1d8a3601d188af2a899da/core/types/transaction_marshalling.go#L30) and this [wishlist](https://gist.github.com/ryanschneider/723d8e2bce0829de9d6beb43639b6d3e).

EIP-2718 rpc `type` field support

---

client/rpc/src/eth.rs

- Use versioned `extrinsic_filter` on pending transactions rpc.
- Use versioned `current_block` in `eth_call` when no gas limit.

Versioned runtimes fixes

---

Cargo.lock
client/db/Cargo.toml
client/db/src/lib.rs
client/rpc/Cargo.toml
client/rpc/src/eth.rs
client/rpc/src/lib.rs
client/rpc/src/overrides/mod.rs
frame/ethereum/src/lib.rs
primitives/storage/Cargo.toml
primitives/storage/src/lib.rs
template/node/Cargo.toml
template/node/src/rpc.rs

By moving `EthereumStorageSchema` from the pallet-ethereum to primitives, decouple the pallets from the client db/rpc module.
Oher custom ethereum-pallet can reuse the client part code after this.

Move `EthereumStorageSchema` to primitives

---

Cargo.lock
Cargo.toml
client/consensus/Cargo.toml
client/consensus/src/lib.rs
frame/ethereum/Cargo.toml

use `thiserror` instead of `derive_more` for error handling

---

client/rpc-core/Cargo.toml

Compiling `rpc-core` alone will report compile errors, which should be caused by `resolver = "2"`

Fix `rpc-core` compile error

---

client/rpc/src/eth.rs
ts-tests/tests/test-contract.ts

To match ethereum mainnet and other evm compatible chains behaviout as reported [here](https://github.com/PureStake/moonbeam/issues/1301).

`eth_call` return code instead address

---

frame/ethereum/Cargo.toml
frame/ethereum/src/lib.rs

This bug can be reproduced after storage upgrade from `BlockV0` to `BlockV2`, and only if the preceding block contained transactions. In that case the `current_block_hash` function will try to decode `BlockV2`, failing to do so because the block contains `TransactionV0`s and returning `None`, defaulting to `H256::default()`, rendering the parent hash useless and of course messing the block hashing of the subsequent blocks.
This PR proposes just use the already existing `BlockHash` storage and query it using the previous block number.
This is a pretty nasty bug and should merged in asap @sorpaas . Also, do you have any suggestion on how to test this type of situation in frontier?

Fix bug parent hash on `BlockV2` upgrade

---

client/rpc/src/eth.rs

A new `ApiRef` instance needs to be used per execution to avoid the overlayed state to affect the estimation result of subsequent calls.
Note that this would have a performance penalty if we introduce gas estimation for past blocks - and thus, past runtime versions - in the future. Substrate has a `runtime_cache_size` (introduced in https://github.com/paritytech/substrate/pull/10177) which defaults to 2 slots LRU-style, meaning if users were to access multiple runtime versions (more than 2) in a short period of time, the RPC response time would degrade a lot, as the `VersionedRuntime` needs to be compiled to occupy a slot. 
To solve that, and if we introduce historical gas estimation, we'd need to increase value.

Fresh runtime api instance per call estimation

---

client/db/src/lib.rs
client/mapping-sync/src/lib.rs
client/mapping-sync/src/worker.rs
template/node/src/service.rs

For chains that want to install frontier pallets mid-flight, the mapping-sync-worker helps extract the block and transaction information from the header digest and writes it to rocksDB for all history blocks. When the original chain is high enough(1M above), the problem arises. During this time, the node can easily become stuck due to intensive calculations.
I do some changes in the `sync_blocks` strategy and only track and sync these blocks with frontier digest. Another change is making the `retry_limit` configured. I shorten the default retry times from 8 to 3. Everything works fine in my tests.

Only trace block with digest

---

frame/base-fee/src/lib.rs

It is not a good idea to deposit this event so frequently(each block).

No need to deposit event each block

---

template/runtime/Cargo.toml

Remove `frame-benchmarking` and `frame-system-benchmarking `from the std feature of runtime

---

frame/ethereum/src/lib.rs

The current implementation will store the `Pending` on-chain, but I don't think it's necessary

pallet-ethereum: kill `Pending` storage when finalizing block

---

client/rpc/src/eth/execute.rs

When `rpc_binary_search_estimate` is available we don't care about estimate mode. Just use regular, non-transactional evm calls, including the first call.

Do not enter `evm` estimate mode when binary search flag is enabled

---

Cargo.lock
frame/base-fee/src/lib.rs
frame/dynamic-fee/src/lib.rs
frame/ethereum/src/lib.rs
frame/ethereum/src/mock.rs
frame/ethereum/src/tests/eip1559.rs
frame/ethereum/src/tests/eip2930.rs
frame/ethereum/src/tests/legacy.rs
frame/evm/src/lib.rs
frame/evm/src/mock.rs
frame/evm/src/runner/mod.rs
frame/evm/src/runner/stack.rs
frame/evm/src/tests.rs
primitives/evm/Cargo.toml
primitives/evm/src/lib.rs
template/runtime/src/lib.rs

Currently in `pallet-ethereum`, we call the `execute` function assuming a fully validated transaction and calling `expect` over the runner's `Result`.
This PR:
- Adds missing `max_fee_per_gas >= max_priority_fee_per_gas` validation condition. Without this, transactions sent through RPC are submitted to the pool and later fail on `apply` (because this check is performed in the runner), causing the **panic** on `pallet-ethereum` `execute` call.
- Handles the eventual error in `pallet-ethereum` instead of panicking. Again, as we expect the transaction to be fully validated, this should never happen. But because `pallet-evm` and `pallet-ethereum` are two different paths that ultimately interface with the evm, redundant validation on both sides is necessary, and if they are not totally aligned …

Pre-validation fixes and dispatch error handling 

---

Cargo.lock
client/rpc-core/src/web3.rs
template/node/src/command.rs

```bash
cargo update -p sp-std --precise 1e0807fb477b21edd373eb88778336d5ff23d3a7
```
NOTE: polkadot-v0.9.20 and polkadot-v0.9.21 use the same substrate commit

update substrate to the polkadot-v0.9.20

---

Cargo.lock
Cargo.toml
client/rpc/Cargo.toml
frame/ethereum/Cargo.toml
frame/evm/Cargo.toml
frame/evm/precompile/blake2/src/lib.rs
frame/evm/precompile/bn128/src/lib.rs
frame/evm/precompile/dispatch/src/lib.rs
frame/evm/precompile/modexp/src/lib.rs
frame/evm/src/lib.rs
frame/evm/test-vector-support/Cargo.toml
frame/evm/test-vector-support/src/lib.rs
primitives/evm/Cargo.toml
primitives/evm/src/lib.rs
primitives/evm/src/precompile.rs
template/runtime/src/precompiles.rs

Companion to https://github.com/rust-blockchain/evm/pull/122

EVM PrecompileHandle companion

---

frame/evm/src/lib.rs
frame/evm/src/runner/stack.rs
frame/evm/src/tests.rs

The motivation for this is, currently is not possible to reproduce the Ethereum behaviour, as it was previously noticed by @icodezjb in https://github.com/paritytech/frontier/pull/646, although that proposal was initially discarded because it didn't fullill some of the use cases (i.e. ability of not paying the author, even if there are priority fees).
This PR changes the `OnChargeEVMTransaction` trait to handle base fee and tip fees separately:
- `correct_and_deposit_fee` will issue the refund and call on_unbalanced with just the base fee, returning the `NegativeImbalance` of the eventual tip.
- `pay_priority_fee` takes the `NegativeImbalance` as an argument.
This way one can:
- Handle the fees in the Ethereum way: burn the base fee `on_unbalanced` and pay the remaining …

Split base fee and tip handling

---

client/rpc-core/src/types/block.rs
client/rpc/src/eth/mod.rs
client/rpc/src/eth_pubsub.rs
ts-tests/tests/test-block.ts
ts-tests/tests/test-subscription.ts

Replace parity/open-ethereum's `seal_fields` field by the more adopted `nonce`, which is compatible with libraries (web3js, ethers), thus less prone to break existing Dapps.
We are zero defaulting `mix_hash` and `nonce` anyway.

Replace `seal_fields` with `nonce`

---

primitives/evm/src/validation.rs

Fixes a minor discrepancy with EIP-1559 specification on how account balance must be validated against transaction input. 
Currently we validate a transaction using the provided `max_fee_per_gas`, which in some cases is requiring the sender to have more free balance than the strictly necessary to submit or apply it. This PR proposes changing that to validate a transaction using:
- The `effective_gas_price`* in case of eip-1559 transactions.
- The provided `gas_price` for legacy and eip2930 transactions.
*`effective_gas_price = MIN( (base_fee + max_priority_fee_per_gas), max_fee_per_gas )`
Additionally I added some more test coverage for legacy input.

Validate balance against effective gas price

---

Cargo.lock
frame/ethereum/Cargo.toml
frame/ethereum/src/lib.rs
primitives/ethereum/Cargo.toml
primitives/ethereum/src/lib.rs

- Move `TransactionData` and it's impls to a new `fp-ethereum` so it can be used by external code.
- Implements the new `ValidatedTransaction` trait in `pallet-ethereum` to interface with `apply_validated_transaction`.

`fp-ethereum` refactor

---

frame/ethereum/src/lib.rs
frame/ethereum/src/mock.rs
primitives/self-contained/src/checked_extrinsic.rs
primitives/self-contained/src/lib.rs
template/runtime/src/lib.rs

We realized at moonbeam that the dispatch class limits did not apply to ethereum transactions.
As a result, ethereum transactions can fill the entire 'n block by weight, without respecting the `NORMAL_DISPATCH_RATIO`.
This bug is due to the fact that the application of limits by dispatch class is done only in `CheckWeight::pre_dispatch`, and the actual frontier code does not use CheckWeight in `pre_dispatch_self_contained`.
This PR fix that.

fix(frame): CheckWeight controls should be applied on pre_dispatch

---

frame/evm/precompile/blake2/src/lib.rs
frame/evm/precompile/bn128/src/lib.rs
frame/evm/precompile/modexp/src/lib.rs

Now that we're recording gas using the `PrecompileHandle`, it can be done as soon as the cost is known. Since `record_cost` handles Out of Gas, it is no longer necessary to check it manually.

Remove redundant gas checks in precompiles

---

template/node/Cargo.toml

We need to include with-rocksdb-weights feature for the runtime to compile properly.

add with-rocksdb-weights

---

Cargo.lock
frame/evm/precompile/dispatch/Cargo.toml
frame/evm/precompile/dispatch/src/lib.rs
frame/evm/precompile/dispatch/src/mock.rs
frame/evm/precompile/dispatch/src/tests.rs

Add a type parameter to configure a depth limit when decoding the call data.
Otherwise it is possible to craft a arbitrarily deep nested call that can overflow the stack.

Dispatch precompile: decode call with depth limit

---

client/rpc-core/src/types/receipt.rs
client/rpc/src/eth/transaction.rs
ts-tests/tests/test-revert-receipt.ts

@sorpaas this is a complementary change to what we talked about receipt root calculation. This is part of the expected response payload (https://github.com/ethereum/go-ethereum/blob/master/core/types/receipt.go#L54), and is used by dapps to perform the offchain receipt proof verification.

`type` field for rpc `Receipt` response payload

---

primitives/evm/src/validation.rs

Transaction cost must only be validated on transactional context. Otherwise, on gas estimation, validation error will propagate as part of the rpc response, instead capturing the `ExitError` naturally returned by the EVM.

Do not validate transaction cost on non-transactional context

---

frame/evm/src/benchmarking.rs
template/node/src/chain_spec.rs

Benchmark in `pallet-evm` is not working.
This pull request fix this error by adding benchmark account in chan spec file, adjust some gas settings.

fix evm benchmarks

---

frame/evm/src/runner/stack.rs

pallet-evm: use `u32::MAX` instead of deprecated `u32::max_value()`

---

client/rpc/src/eth/execute.rs
client/rpc/src/eth/mod.rs
primitives/evm/src/validation.rs
template/node/src/rpc.rs
ts-tests/tests/test-execute.ts
ts-tests/tests/test-gas.ts

Infura allows to use eth_call/eth_estimateGas with up to 10x the block gas limit:
https://docs.infura.io/infura/networks/ethereum/json-rpc-methods/eth_call
To replicate this feature :
- Runtime gas limit check is made only if call is transactional.
- Client RPC have a configurable factor, and will ensure the requested gas limit is less than the block gas limit times the factor.

Allow larger gas limit in non-transactional execution

---

client/rpc/src/eth/mod.rs
ts-tests/tests/test-balance.ts
ts-tests/tests/test-contract.ts

1. The result of the pending query is not necessarily the final result (for example, inserting many transactions in the next second causes the previous transaction to expire, or the block may be rolled back) just to provide a reference value.
2. The current pending_runtime_api implementation will report the following panic for Aura consensus.
- 1. steps to reproduce
```
cargo build --release
./target/release/frontier-template-node --tmp --dev --rpc-port 8546
curl -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "method": "eth_getBalance", "params": ["0x77777FeDdddFfC19Ff86DB637967013e6C6A116C","pending"],"id": 1}' http://127.0.0.1:8546
get error:
{"jsonrpc":"2.0","error":{"code":-32603,"message":"Runtime api access error: Application(Execution(RuntimePanicked(\"Slot must …
```

Fix panic in pending_runtime_api with Aura consensus env

---

client/rpc/src/eth/execute.rs

Our current code in parsing the EVM revert reason is incorrect in two ways. First, the length is a big-endian encoded U256, not a simple sum. Second, the current summing function uses the accumulator type of `u8` which will overflow easily. The current code only works because most EVM revert reasons are not larger than 256 bytes.

Fix length checking overflow in EVM revert reason parsing

---

Cargo.lock
template/node/src/benchmarking.rs
template/node/src/command.rs
template/node/src/main.rs
template/runtime/src/lib.rs

update substrate to the commit 782e08ed36e3c3e5ffa3a48484267b02ec8b7b6d, prepare for releasing polkadot-v0.9.27

Update substrate to polkadot-v0.9.27

---

Cargo.lock
Cargo.toml

There were 2 minor releases after polkadot-sdk 1.7.0
- https://github.com/paritytech/polkadot-sdk/releases/tag/polkadot-v1.7.1
- https://github.com/paritytech/polkadot-sdk/releases/tag/polkadot-v1.7.2

deps: update dependencies to polkadot-v1.7.2

---

frame/ethereum/src/lib.rs

Hi
I guess it was a typo after [removing deprecated getters](https://github.com/polkadot-evm/frontier/pull/1034/files#diff-4a4404da981c8fc7fd4a5f9245136407d480ae2568de69e207c12066cb9473f5). All other storages of `pallet-ethereum` remove their `super` visibility except `Pending` storage. Blocking any interaction with it from the outside.
This PR removes the `super` visibility to be able to access them from other pallets.

Fix: Remove `super` visibility of `Pending` storage in `pallet-ethereum`

---

frame/ethereum/src/lib.rs

Replicate https://github.com/polkadot-evm/frontier/pull/1346 for `polkadot-v1.1.0`

Fix: Remove super visibility of Pending storage in pallet-ethereum

---

precompiles/src/precompile_set.rs

Adds an additional getter for `used_addresses` in the `PrecompileSetBuilder`.
Unlike the existing one which returns mapped addressed, the new one returns `H160` addresses.
Perhaps it would be best to remove the old one, but I've kept it for backwards compatibility.

used_addresses_h160 getter for the PrecompileSetBuilder

---

Cargo.lock
template/runtime/Cargo.toml
template/runtime/src/lib.rs

The current benchmark runtime api implementation is problematic, this pr fix it with some code clean in the template runtime file.
Note: I delete the `pallet_hotfix_sufficients` pallet from the template runtime, since this is a patch in the two years ago. It would be confusing for the new frontier developers to keep it in the template node.

Fix benchmark runtime api

---

.github/workflows/lint.yml

Don't run github actions when only `.md` files are changed. 
This will: 
- save resources (for the quota of the repo), 
- pull-requests can be merged faster,
- less electric consumption 🌱

ignore md files for workflows

---

client/rpc/src/eth/execute.rs

This PR https://github.com/polkadot-evm/frontier/pull/1257 introduced a regression that make the client not compatible with old runtimes.
Old runtimes doesn't check properly non transactional evm calls, old runtimes rely on the fact that max_fee_per_gas is None to consider the evm call non transactional.
It introduced a bug in Moonbeam where eth_call against past blocks produce the `BalanceLow` error.
Because we can't change old runtimes, the client should not set `max_fee_per_gas` as `Some(zero)`, otherwize old runtimes will assume that the evm call is transactional.

support eth_call for past blocks with old runtimes

---

client/rpc/src/eth/execute.rs
template/runtime/src/lib.rs

This PR [#1257](https://github.com/polkadot-evm/frontier/pull/1257) introduced a regression that make the client not compatible with old runtimes.
Old runtimes doesn't check properly non transactional evm calls, old runtimes rely on the fact that `max_fee_per_gas` is None to consider the evm call non transactional.
It introduced a bug in Moonbeam where `eth_call` and `estimate_gas` against past blocks produce the BalanceLow error.
Because we can't change old runtimes, the client should not set max_fee_per_gas as Some(zero), otherwize old runtimes will assume that the evm call is transactional.
I submitted a PR upstream (polkadot-evm/frontier#1404) to fix it for `eth_call`, but we have the same bug with `estimate_gas`, this PR move the fix into the `fee_details` function itself.

Fix estimate gas for old runtimes

---

Cargo.lock
Cargo.toml
client/rpc/Cargo.toml
client/rpc/src/net.rs
template/node/src/command.rs
template/node/src/rpc/eth.rs
template/node/src/service.rs
template/runtime/Cargo.toml
template/runtime/src/lib.rs
ts-tests/tests/util.ts

Probably worth checking that everything is alright!

deps: update substrate to release-polkadot-v1.11.0

---

Cargo.lock
Cargo.toml
client/db/src/sql/mod.rs
client/mapping-sync/src/sql/mod.rs
client/rpc/Cargo.toml
frame/evm/precompile/modexp/Cargo.toml
template/node/Cargo.toml
template/node/src/benchmarking.rs
template/node/src/client.rs
template/node/src/eth.rs
template/node/src/rpc/eth.rs
template/node/src/rpc/mod.rs
template/node/src/service.rs
template/runtime/src/lib.rs

- update substrate deps to release-polkadot-v1.12.0 branch
- improve template node
Close #1433 
Close #1434 
Close #1435 
Close #1436

deps: update substrate to polkadot-v1.12.0

---

frame/base-fee/src/lib.rs

It's not a critical thing, but it's better to have small description/summary for each pallet in `src/lib.rs`. For example, you guys already have that for `pallet-ethereum`.
I had to check to source-code and read all the code of `basefee pallet` to understand what this pallet does just to be sure. 
Added the inline docs as a draft, feel free to change it or merge it as is.

basefee pallet inline docs for pallet description

---

Cargo.lock
Cargo.toml
client/consensus/src/lib.rs
frame/evm/precompile/dispatch/src/mock.rs
frame/evm/src/mock.rs
rust-toolchain.toml
template/node/src/chain_spec.rs
template/runtime/src/lib.rs

update polkadot-sdk deps to stable2407

---

primitives/account/src/lib.rs

This PR fixes the following issue.
---
When building `fp-account` without default features with the command:
```sh
cargo build -p fp-account --no-default-features --target wasm32-unknown-unknown
```
an error will occur because `core::fmt::FromStr` is not implemented for `H160` without default features.
```sh
Checking fp-account v1.0.0-dev (/Users/conr2d/Projects/frontier/primitives/account)
error[E0599]: no function or associated item named `from_str` found for struct `H160` in the current scope
--> primitives/account/src/lib.rs:51:9
|
51 |         H160::from_str(s)
|               ^^^^^^^^ function or associated item not found in `H160`
|
```

fix: Fix FromStr not found error on AccountId20

---

frame/evm/src/runner/stack.rs

Improve the handling of EVM reentrancy and simplify the codebase. The most important changes include modifying the `IN_EVM` environmental variable, updating the execution logic to handle reentrancy, and ensuring proper cleanup after execution.

Refactor EVM recursion lock

---

client/rpc/src/eth/execute.rs
ts-tests/tests/test-gas.ts

The RPC method `eth_estimateGas` takes a Transaction object with a nonce field, the client requires that this nonce is equal to the current on-chain user nonce + 1. This a discrepancy with `geth` behavior, which always ignores the nonce field. Now, the field is still there to not break the RPC api but not used.

Ignore user provided nonce when estimating gas

---

client/api/src/backend.rs
client/db/src/kv/mod.rs
client/db/src/sql/mod.rs

This pull request introduces a new method to fetch the hash of the first substrate block in the backend. This will enables the ability to get the range of blocks that are fully indexed in frontier's backend.

Add backend method first_block_hash

---

client/rpc/Cargo.toml
client/rpc/src/eth/pending.rs

Close #1514.
This PR makes the `fc-rpc` dependencies on Aura consensus-specific crates optional.

feat: Make fc-rpc dependencies on aura crates optional

---

Cargo.lock
frame/evm/src/runner/meter.rs
frame/evm/src/runner/stack.rs
primitives/evm/Cargo.toml
primitives/evm/src/lib.rs
primitives/evm/src/storage_oog.rs

Fixes issue where a TX that reaches out of gas due to PoV costs would revert without propagating a proper OOG error

Fix: propagate OOG from PoV

---

frame/ethereum/src/lib.rs

The `Pending` state is a list that is used to keep track of all the `(transaction, status, receipt)` in the block during block execution, and then in `on_finalize` these data are moved to `CurrentBlock/CurrentReceipts/CurrentTransactionStatuses` for RPC service usage.
Because the `Pending` state is a `StorageValue<_, Vec<...>>`, which presents as a single value in the trie, appending items to the list means read,update,write to the same value, which gets slower and slower as the list grows during block execution, and depend on the number of tx in the block it can result in 3-20x of slow (see below).
This PR fixes the issue by refactoring the `Pending` state, to replace `StorageValue` with `StorageMap` so each tx is present as a single value in the trie, although it results in more db …

Fine-grained `Pending` state

---

client/rpc-core/src/types/filter.rs

VariadicValue::Multiple variant should be bounded to prevent heavy computation on cartesian product.
This is a continuation of #1488 where `VARIADIC_MULTIPLE_MAX_SIZE` has been increased to 1024.

bound VariadicValue multiple variant

---

client/rpc-core/src/eth.rs
client/rpc-core/src/types/block_count.rs
client/rpc-core/src/types/mod.rs
client/rpc/src/eth/fee.rs
client/rpc/src/eth/mod.rs

Allow to specify integer as `block_count` for `eth_feeHistory`

Allow to specify integer as `block_count` for `eth_feeHistory`

---

frame/evm/precompile/simple/src/lib.rs

The ECRecover precompile was already returning an empty vector for invalid v values, but the comment wasn't clear about handling high bits. This commit updates the comment to be more explicit about checking for any set high bits in the v value (bytes 32-62 must be 0) and that v (byte 63) can only be 27 or 28.
Fixes TODO comment regarding "InvalidHighV-bits-1" test case.

fix: handle invalid high bits in ECRecover v value

---

template/node/Cargo.toml

In #1580, the Aura consensus implementation in `fc-rpc` was made feature-gated by the "aura" flag. Since default features are disabled for `fc-rpc`, the Frontier template node now requires the aura feature to be explicitly enabled.

chore: Enable "aura" feature in fc-rpc for template node

---

precompiles/src/solidity/codec/xcm.rs

**Motivation**
- Downstream dependencies (e.g., `moonkit`) depend on this behavior.
- `/primitives/account/src/lib.rs` already targets `xcm::latest`.
**Suggested Solution**
- Implement solidity codecs on `xcm::latest`.
**Alternative Solution**
- Add feature flag to support both `xcm::lts` and `xcm::latest`.

Implement solidity codecs on xcm::latest

---

Cargo.lock
Cargo.toml
template/runtime/Cargo.toml
template/runtime/src/lib.rs

The template runtime configuration sets FeeMultiplierUpdate to `ConstFeeMultiplier`, which does not take into consideration the current usage of the network. 
While this is a template, it is still good to provide a safe example for anyone integrating frontier in their runtimes.
When using `ConstFeeMultiplier`, fees do not reflect congestion, an attacker could cause a DoS against all zero-tip transactions for an extended period of time by just paying the regular transaction fees (and not exponentially raising fees, which would at least limit the duration of that attack).

Feat: use SlowAdjustingFeeUpdate to update fees based on congestion

---

Cargo.lock
template/node/Cargo.toml
template/node/src/benchmarking.rs
template/runtime/src/lib.rs

Fix `StorageWeightReclaim` usage as wrapper as it is described [here](https://github.com/paritytech/polkadot-sdk/blob/25552a05d1326f82a38c59f07a1a6c0a527ce567/prdoc/stable2503/pr_6140.prdoc)

Fix StorageWeightReclaim usage after updating to polkadot 2503

---

ts-tests/README.md
ts-tests/tests/util.ts

The test suite now supports attaching to an already running Frontier node instead of spawning a new one. This is useful for debugging with a node that has a debugger attached.
Set the `FRONTIER_ATTACH` environment variable before running tests:
```bash
FRONTIER_ATTACH=true npm test
FRONTIER_ATTACH=true npx mocha -r ts-node/register tests/test-eip7702.ts
```
The existing node must be running with these parameters:
- `--rpc-port=19932` (matches test suite expectations)
- `--sealing=manual` (for controlled block production)
- Other standard test parameters as shown in debug.json
1. Start your debug node:
```bash
./target/debug/frontier-template-node \
--chain=dev \
--validator \
--execution=Native \
--sealing=manual \
--no-grandpa \
--force-authoring \
--rpc-port=19932 \
--rpc-cors=all \ …
```

Allow integration tests to attach to a running node
